# backend/export_plan_schema.py

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Literal
from datetime import datetime
import json

# =========================
# Individual Planned Action
# =========================

class ExportWarning(BaseModel):
    code: str
    file_id: Optional[int] = None
    path: Optional[str] = None


class ExportAction(BaseModel):
    """
    One atomic export action.
    """

    action: Literal["copy", "update", "skip", "delete", "mkdir"]

    file_id: Optional[int] = None

    src_path: Optional[str] = None
    dst_path: Optional[str] = None

    reason: Optional[str] = None

    size_bytes: Optional[int] = None
    sha256: Optional[str] = None


# =========================
# Directory Cleanup Info
# =========================

class OrphanDirectory(BaseModel):
    path: str
    will_be_empty: bool
    contains_only_art: bool


# =========================
# Plan Summary
# =========================

class ExportPlanSummary(BaseModel):
    files_total: int = 0

    to_copy: int = 0
    to_update: int = 0
    to_skip: int = 0
    to_delete: int = 0

    dirs_to_create: int = 0
    dirs_to_delete: int = 0

    warnings: int = 0
    errors: int = 0

    estimated_bytes: int = 0


# =========================
# Canonical Export Plan
# =========================

class ExportPlan(BaseModel):
    """
    Canonical export plan.

    This is:
    - Generated by backend
    - Saved to disk
    - Reviewed by user
    - Later executed (or not)
    """

    plan_id: str = Field(..., description="Unique plan identifier")

    preset_id: str
    target_root: str

    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())

    dry_run: bool = True

    # ---- Snapshot Metadata ----

    source_root: str
    library_root: str
    database_path: str

    # ---- Summary ----

    summary: ExportPlanSummary

    # ---- Actions ----

    actions: List[ExportAction] = Field(default_factory=list)

    # ---- Orphan Directories ----

    orphan_directories: List[OrphanDirectory] = Field(default_factory=list)

    # ---- Warnings / Errors ----

    warnings: List[ExportWarning] = Field(default_factory=list)
    errors: List[ExportWarning] = Field(default_factory=list)

    # ---- Safety ----

    requires_confirmation: bool = True
    allow_execute: bool = False

def save_export_plan(plan, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(plan.dict(), f, indent=2)
